image: continuumio/anaconda3
stages:
  - test
  - deploy

test_py27:
  stage: test
  tags:
    - docker
  script:
    - conda env create --file ci/requirements-py27.yml > /dev/null 2>&1
    - source activate test_env
    - python setup.py install
    - py.test

test_py33:
  stage: test
  tags:
    - docker
  script:
    - conda env create --file ci/requirements-py33.yml > /dev/null 2>&1
    - source activate test_env
    - python setup.py install
    - py.test

test_py34:
  stage: test
  tags:
    - docker
  script:
    - conda env create --file ci/requirements-py34.yml > /dev/null 2>&1
    - source activate test_env
    - python setup.py install
    - py.test

test_py35:
  stage: test
  tags:
    - docker
  script:
    - conda env create --file ci/requirements-py35.yml > /dev/null 2>&1
    - source activate test_env
    - python setup.py install
    - py.test

test_py36:
  stage: test
  tags:
    - docker
  script:
    - conda env create --file ci/requirements-py36.yml > /dev/null 2>&1
    - source activate test_env
    - python setup.py install
    - py.test

deploy_docs:
  stage: deploy
  tags:
    - docker
  script:
    - conda env create --file docs/environment.yml > /dev/null 2>&1
    - source activate doc_env
    - python setup.py install
    - cd docs
    - make html
    - cp -r build/html/* /media/users/djz828/regression_docs/