image: continuumio/anaconda3
stages:
  - test

test_py36:
  stage: test
  tags:
    - docker
  script:
    - conda env create --file ci/requirements-py36.yml
    - source activate test_env
    - python setup.py install
    - nosetests