name: doc_env
dependencies:
  - python=3.6
  - numpy
  - pandas
  - scipy
  - statsmodels
  - matplotlib
  - ipython
  - jupyter
  - pandoc
  - netcdf4
  - hdf5
  - pip:
    - sphinx
    - sphinx_rtd_theme
    - nbsphinx
    - pandoc